### DISCUSSION TITLE
Replace Redis with Garnet in docker-compose v2.4

### DISCUSSION THREAD

**Discussion by Misiu** [microsoft/garnet#1172] [Q&A] [answered]
I'm trying to replace Redis with Garnet in my docker-compose file.
I'm limited to version 2.4 because the solution will run on balena.io on Raspberry Pi 4 and 5.

Currently, I have this part:
```
version: '2'
services:
  cache:
    image: redis:7.4
    expose:
      - "6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
```

Replacing the image is the easy part, but the rest is problematic.
I'd like to add healthcheck to this container, but I don't see an equivalent to redis-cli in garnet.
What command can I use to check if the container is healthy?
