### DISCUSSION TITLE
How to use the cluster mode with replicas in kubernetes?

### DISCUSSION THREAD

**Discussion by Christian-Steusloff** [microsoft/garnet#1181] [Q&A]
I am trying to deploy garnet within the kubernetes environment using the helm script provided, to create an always-on-system.

I have created the following values.yaml file:
```yaml
statefulSet:
  replicas: 3
  revisionHistoryLimit: 10
image:
  tag: "latest"
config:
  garnetConf: |
    {
      "EnableCluster": true,
      "EnableStorageTier": true,
      "checkpointdir" : "data/",
      "EnableAOF": true
    }
 ```
 
 Deploy the pods with helm install
 ```shell
helm upgrade --install garnet oci://ghcr.io/microsoft/helm-charts/garnet -f .\values.yaml -n garnet
 ```
 
![image](https://github.com/user-attachments/assets/51d4abc1-9a39-46c2-a044-a5d8f5b56553)
I then created a cluster manually (https://microsoft.github.io/garnet/docs/cluster/overview). Can this also be done automatically with helm deployment?
![image](https://github.com/user-attachments/assets/d678e65a-ae1b-4a71-977e-8989aa11ded3)

I cannot access the KEYS or create new KEYS via the service in Kubernetes. How should I access them?

Furthermore, I cannot find an option for the FAILOVER. How can an always-on system be realized with garnet?

Thanks
