### DISCUSSION TITLE
How to config password in docker compose?

### DISCUSSION THREAD

**Discussion by vimutti77** [microsoft/garnet#204] [Q&A] [answered]
I try to config the password by using adding `command --password 12345678`. But it still not required the password.
```yml
  garnet:
    image: ghcr.io/microsoft/garnet
    ulimits:
      memlock: -1
    volumes:
      - garnetdata:/data
    ports:
      - "6379:6379"
    command: --password 12345678
```

**Comment by badrishc** [comment]
@XiaoHeitu and @Niek - any idea on integration of command line args here?

**Comment by Misiu** [comment]
Do you happen to have any updates on this?
I want to replace Redis in Dev env and I need to be able to set password.

With Redis we can simply do:
```
  myredis:
    image: docker.io/bitnami/redis:7.2
    environment:
    - REDIS_PASSWORD=mysecret
    expose:
    - "6379"
    ports:
    - "6379:6379"
    restart: unless-stopped
    networks:
    - myredis
```

**Comment by akoken** [comment, marked as answer]
@Misiu That should work:

```yaml
services:
    garnet:
        ulimits:
           memlock: -1
        image: ghcr.io/microsoft/garnet
        volumes:
            - garnet-data:/data
        ports:
            - "6379:6379"
        command: --auth Password --password <replace_password_here>

volumes:
    garnet-data:
```
