### ISSUE TITLE
Notice of wrong startup string but correct processing.

### ISSUE THREAD

**Issue by pomazanbohdan** [microsoft/garnet#126]
docker-compose.yml:
```
services:
  garnet:
    image: yzy613/garnet:latest
    # image: altall/garnet:v1.0.0
    container_name: garnet
    command:
      /app/GarnetServer.exe --config-import-path /data/config/garnet.json
```

garnet  |     _________
garnet  |    /_||___||_\      Garnet 1.0.1 64 bit; standalone mode
garnet  |    '. \   / .'      Port: 3278
garnet  |      '.\ /.'        https://aka.ms/GetGarnet
garnet  |        '.'
garnet  |
garnet  | 08::40::57 info: GarnetServer[0] Garnet 1.0.1 64 bit; standalone mode; Port: 3278
garnet  | 08::40::57 info: ArgParser[0] Configuration import from embedded resource succeeded. Path: defaults.conf.
garnet  | 08::40::57 warn: ArgParser[0] The following command line arguments were not parsed: /app/GarnetServer.exe.  Please check the syntax of your command. For detailed usage information run with --help.
garnet  | 08::40::57 info: ArgParser[0] Configuration import from local machine succeeded. Path: /data/config/garnet.json.
