### ISSUE TITLE
[Question] ipv6 support for garnet?

### ISSUE THREAD

**Issue by wmundev** [microsoft/garnet#208]
Hi garnet team,
thanks for releasing this project as open source! i have been excited to give it a go and see if i can use it as a drop in replacement for a server that is currently hosting redis via docker compose

here is the docker compose file i used for this proof of concept
```
services:
  garnet:
    image: 'ghcr.io/microsoft/garnet'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # To avoid docker NAT, consider `host` mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    command: GarnetServer --auth Password --password abcdefg
    network_mode: "host"
    volumes:
      - garnetdata:/data
volumes:
  garnetdata:
```

after which, i tried connecting to it via redis-cli and 

i tried the ipv6 version
```
redis-cli -h [xxxx:xxxx:xxx:xxxx:xxxx:xxx:xxxx:xxxx] -a abcdefg
```
and
```
redis-cli -h xxxx:xxxx:xxx:xxxx:xxxx:xxx:xxxx:xxxx -a abcdefg
```
got a "Network is unreachable" error

the ipv4 version worked fine without any issues
```
redis-cli -h xx.xxx.xx.xx -a abcdefg
```

i have verified that my server has both ipv4 and ipv6 addresses for me to connect to

is ipv6 currently supported in garnet or is this a future feature to be addressed? thanks in advance!
