### ISSUE TITLE
Port number does not match expectations

### ISSUE THREAD

**Issue by shijunpeng15** [microsoft/garnet#454]
### Describe the bug

When I pulled the image and ran it, I checked the running commands as follows: [./GarnetServer - i 128m -- port 6379] [-- config import path/app/garnet. json].
The port number used for execution was not declared in the garnet.json file, and it is also not 3278.

My docker-compose.yml:
```
 version: '3.8'
services:
  garnet:
    restart: always
    privileged: true
    image: 'ghcr.io/microsoft/garnet'
    container_name: garnet
    ulimits:
      memlock: -1
    ports:
      - "6370:6379"   # 6370:6370
    network_mode: "bridge"
    volumes:
      - /usr/local/docker/garnet/garnet.json:/app/garnet.json
      - /usr/local/docker/garnet/data:/data
      - /usr/local/docker/garnet/logs:/logs
    command: --config-import-path /app/garnet.json
```
My garnet.json:
```
{
  "Port": 6370,
  "Address": "0.0.0.0",
  "AuthenticationMode": "Password",
  "Password": "123456",
  "EnableAOF": true,
  "Recover": true
 "CheckpointDir":"/logs"
}

```

### Steps to reproduce the bug

...
