### ISSUE TITLE
GarnetServer ignores maxthreads and cluster arguments

### ISSUE THREAD

**Issue by httpjamesm** [microsoft/garnet#602]
### Describe the bug

When running GarnetServer with the command line arguments `--maxthreads 4`, `--minthreads 1`, `--cluster false`, it continues to fork into dozens of processes instead of abiding by the maximum thread limit.

### Steps to reproduce the bug

1. Create docker compose file like so:
```yml
  garnet:
    image: ghcr.io/microsoft/garnet-alpine
    ulimits:
      memlock: -1
    restart: always
    network_mode: 'host'
    volumes:
      - garnetdata:/data
      - ./cfg:/cfg
    command: --maxthreads 4 --minthreads 1 --memory 1GB --cluster false
```

2. Run it with `docker compose up -d`
3. Observe the dozens of processes created by Garnet

### Expected behavior

I expected Garnet to not fork into dozens of processes - just 4.

### Screenshots

![image](https://github.com/user-attachments/assets/0d117d67-7d04-42a1-8236-77f2d11f1f12)

### Release version

Garnet 1.0.18 64 bit; standalone mode

### OS version

Docker Alpine
