### ISSUE TITLE
[helm-chart] Bad substition in the workflow generating the package

### ISSUE THREAD

**Issue by babykart** [microsoft/garnet#850]
### Describe the bug

The `Chart.yaml` file generated by the workflow :

```yaml
apiVersion: v2
appVersion: ${VERSION_PROPS}
description: A Helm chart for Microsoft garnet
home: https://github.com/microsoft/garnet
icon: https://avatars.githubusercontent.com/u/6154722?s=200&v=4
keywords:
- garnet
- database
- key
- value
- in-memory
name: garnet
sources:
- https://github.com/microsoft/garnet.git
type: application
version: 0.1.2
```

### Steps to reproduce the bug

```
helm pull oci://ghcr.io/microsoft/helm-charts/garnet
```

```
tar -xvzf garnet-0.1.2.tgz
```
